### PR TITLE
Fix blocking call when deleting previous challenges

### PR DESCRIPTION
**Pull request by Arooba-git**
Hello :) 
Thank you for this handy project!

This PR fixes a blocking call and consequently a failing test case in WebFluxClient tests:
Screen Shot 2023-07-28 at 2 49 44 PM

Screen Shot 2023-07-28 at 2 56 46 PM

### CODE REVIEW

**Comment by bmd007** [comment]
I accidentally merged your PR. Then I merged the revert of it. Please feel free to create a new PR.

**Comment by Arooba-git** [comment]
> btw, you seem like an AI agent?! Did I get it right?

Haha no I'm a human 😅 . Actually as part of our research we are going through projects containing blocking calls and submitting fix PRs, to gauge developers responses. As we had a tight schedule , some PRs have some portions of text copy pasted (as our approach remains the same), but the detected bugs, of course, are unique to projects :) 

@bmd007 

> Mono.fromRunnable is a change in a place were there is no problem.

Could you kindly elaborate a bit more on this? 🤔

**Comment by bmd007** [comment]
Great response, thanks.

I reckoned something about fixing blocking calls is going on.

The intention with .block here is to make sure previous challenges are deleted before the actual test code runs. (Clean up, so to say).

To solve that non blocking ly we can connect it to the main test code stream by wrapping it with delay until.

The issue with your approach is that I'm not sure if the runnable is using all the reactive magic. Maybe it does.

**Comment by Arooba-git** [comment]
> the runnable is using all the reactive magic

Oh.. honestly I'm not pro at reactive programming but AFAIK, the `then` operator is simply used to wait for the previous operation to complete to execute the mono passed to it right? so I still don't get how the mono.fromRunnable wrapper is disrupting the reactiveness of pipeline the pipeline 🤔

**Pull request merged**
